title: Chaotic Kingdoms
author:
  name: Chaotic Kingdoms
  email: 'info@chaotic-kingdoms.com'
metadata:
    description: 'Somos empresa dedicada al diseño, desarrollo y monetización de aplicaciones móviles y aplicaciones web'

