home:
  alias: '/home'

pages:
  theme: chaotic
  markdown_extra: true
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

debugger:
  enabled: false
  twig: false
  shutdown:
    close_connection: true

images:
  default_image_quality: 85
  cache_all: true 
